export {default as NavbarComponent} from './Navbar/Navbar'
export {default as Preface} from './Preface/Preface'
export {default as Footer} from './Footer/Footer'
export {default as ImageGrid} from './ImageGrid/ImageGrid'
export {default as SolutionsList} from './Solutions'